name: Build
on: [push, pull_request]

jobs:
  build_app:
    runs-on: ubuntu-latest
    container: aignacio/mpsoc_sw:latest
    steps:
      - name: Run cmake
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: |
          cd sw/histogram_app/
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          make all -j2
